language: ruby

rvm:
  - 1.9.3
  - 2.2.3

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - gem install bundler

before_script:
  - chmod 777 ./config/ci/before-travis.sh
  - ./config/ci/before-travis.sh

script:
  - export DISPLAY=:99.0
  - EXTJS_SRC=cdn bundle exec rake

branches:
  only:
    - master
    - 0-12
